# Generated by Django 4.2.11 on 2024-04-22 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lead',
            name='converted_date',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='date_added',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='description',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='email',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='phone_number',
        ),
    ]
